// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsFqgsDKlDj672HqNz0JZFLpGoUrxJ3l8',
    appId: '1:822672248166:web:f14ad5b4791ace59230ca7',
    messagingSenderId: '822672248166',
    projectId: 'studentlist-e8e9e',
    authDomain: 'studentlist-e8e9e.firebaseapp.com',
    storageBucket: 'studentlist-e8e9e.firebasestorage.app',
    measurementId: 'G-Z54J4ZNE9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt4jrfo0x3JxldZlTS10cQFTDwTR8_my8',
    appId: '1:822672248166:android:e07dbd5bf8e852f1230ca7',
    messagingSenderId: '822672248166',
    projectId: 'studentlist-e8e9e',
    storageBucket: 'studentlist-e8e9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAHmLLE2l0YaeUbV_rpm6NBWWNLmXCUo0',
    appId: '1:822672248166:ios:f1a955f67cd7e3d6230ca7',
    messagingSenderId: '822672248166',
    projectId: 'studentlist-e8e9e',
    storageBucket: 'studentlist-e8e9e.firebasestorage.app',
    iosBundleId: 'com.example.studentlistFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAHmLLE2l0YaeUbV_rpm6NBWWNLmXCUo0',
    appId: '1:822672248166:ios:f1a955f67cd7e3d6230ca7',
    messagingSenderId: '822672248166',
    projectId: 'studentlist-e8e9e',
    storageBucket: 'studentlist-e8e9e.firebasestorage.app',
    iosBundleId: 'com.example.studentlistFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsFqgsDKlDj672HqNz0JZFLpGoUrxJ3l8',
    appId: '1:822672248166:web:0140c695a5b75c9e230ca7',
    messagingSenderId: '822672248166',
    projectId: 'studentlist-e8e9e',
    authDomain: 'studentlist-e8e9e.firebaseapp.com',
    storageBucket: 'studentlist-e8e9e.firebasestorage.app',
    measurementId: 'G-GE6Z4VXZNR',
  );
}
